### PR TITLE
Add `extract` function for deconstruction

### PR DESCRIPTION
**Pull request by gfontenot**
This function extracts the value or throws the error.

As per discussion in #56 /cc @radix
Depends on #57

### CODE REVIEW

**Comment by robrix** [comment]
#57 has been merged :white_check_mark:

**Comment by robrix** [comment]
Just wanted to reflect upon @neilpa’s [suggestion](https://github.com/antitypical/Result/pull/56#issuecomment-110517858) a bit more:

> Throwing out `materialize` and `dematerialize` as names for these.

I kinda like that due to the harmony with RAC. @antitypical/result, anybody have feels?

**Comment by gfontenot** [comment]
Is there any precedent in other languages that we can pull from? I kind of like `extract` for this, since that sounds like a simple but possibly dangerous operation. `dematerialize` sounds overly complex to me.

**Comment by robrix** [comment]
RAC & [Rx](http://reactivex.io/documentation/operators/materialize-dematerialize.html). both use `materialize`/`dematerialize`

**Comment by neilpa** [comment]
> RAC & Rx. both use materialize/dematerialize

Which is why I suggested it.

**Comment by gfontenot** [comment]
:+1: Updated.

**Pull request merged**
