### PR TITLE
Add `LocalizedError` conformance to `AnyError` on Linux with a workaround

### PR DESCRIPTION
**Pull request by ikesyo**
Supersedes #216.

### CODE REVIEW

**Comment by norio-nomura** [comment]
Can we run test with `swift-DEVELOPMENT-SNAPSHOT-2017-05-19-a` on Linux?
Or wait for next `swift-4.0-DEVELOPMENT-SNAPSHOT`?

**Comment by ikesyo** [comment]
I added `DEVELOPMENT-SNAPSHOT-2017-05-21-a` to the build matrix.

**Comment by norio-nomura** [comment]
We need to use `swift test -Xswiftc -swift-version -Xswiftc 4` for confirming `#if swift(>=4.0)` path.

**Comment by norio-nomura** [comment]
Or adding [`swiftLanguageVersions`](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV3.md#swiftlanguageversions) to `Package.swift`.
Without them, SwiftPM builds with `-swift-version 3`.

**Comment by ikesyo** [comment]
Done

**Comment by ikesyo** [comment]
Thanks! 🚢

**Pull request merged**
