### PR TITLE
Add autoclosure attribute to materialize() as with init()

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by ikesyo** [comment]
This can be used as follows:

```
// With this
materialize(try NSFileManager.defaultManager().removeItemAtURL(someURL))
// Without this
materialize { try NSFileManager.defaultManager().removeItemAtURL(someURL) }
```

**Comment by robrix** [comment]
This seems reasonable to me, although I would note that it’s a breaking API change.

@antitypical/result: Any thoughts?

**Comment by gfontenot** [comment]
I'm :+1: on API consistency.

**Comment by robrix** [comment]
That works for me :+1:

**Comment by ikesyo** [comment]
Thanks! :v:

**Comment by robrix** [comment]
Thank _you_!

**Pull request merged**
