### PR TITLE
Change to use `@available(swift, deprecated: 3.0, obsoleted: 3.1, …`

### LINKED ISSUE #212: Build failed on Linux with swift 3.1
Sorry to bother you guys with the pre-released swift version. I just want you to know this issue.

The issue was reported [here](https://bugs.swift.org/browse/SR-3872). And the apple guys confirmed the issue is intended behaviour. The related code is [here](https://github.com/antitypical/Result/blob/master/Result/Result.swift#L128-L135).

This actually won't be an issue once we remove these deprecated methods.

### PR DESCRIPTION
**Pull request by norio-nomura**
Fixes #212

### CODE REVIEW

**Comment by norio-nomura** [comment]
Should we keep them workable?

**Comment by ikesyo** [comment]
Since this is breaking API change now, I think we should choice either of the following:

- Make `master` branch for Swift 3.1
- Prepare `master-next` for Swift 3.1 and `master` is still for Swift 3.0 until we get the official Xcode 8.3 /  Swift 3.1 release.

I prefer the latter.

**Comment by norio-nomura** [comment]
How do you think this?:
```swift
@available(*, deprecated, message: "Use the overload which returns `Result<T, AnyError>` instead")
public func materialize<T>(_ f: @autoclosure () throws -> T) -> Result<T, NSError> {
	#if os(Linux)
		#if swift(>=3.1)
			fatalError("unreachable")
		#else
			do {
				return .success(try f())
			} catch let error as NSError {
				return .failure(error)
			}
		#endif
	#else
		do {
			return .success(try f())
		} catch let error as NSError {
			return .failure(error)
		}
	#endif
}
```

**Comment by norio-nomura** [comment]
Or 
```swift
#if swift(>=3.1)

@available(*, unavailable, message: "Use the overload which returns `Result<T, AnyError>` instead")
public func materialize<T>(_ f: () throws -> T) -> Result<T, NSError> {
	fatalError("unreachable")
}

@available(*, unavailable, message: "Use the overload which returns `Result<T, AnyError>` instead")
public func materialize<T>(_ f: @autoclosure () throws -> T) -> Result<T, NSError> {
	fatalError("unreachable")
}

#else

@available(*, deprecated, message: "Use the overload which returns `Result<T, AnyError>` instead")
public func materialize<T>(_ f: () throws -> T) -> Result<T, NSError> {
	return materialize(try f())
}

@available(*, deprecated, message: "Use the overload which returns `Result<T, AnyError>` instead")
public func materialize<T>(_ f: @autoclosure () throws -> T) -> Result<T, NSError> {
	do {
		return .success(try f())
	} catch let error as NSError {
		return .failure(error)
	}
}

#endif
```

**Comment by norio-nomura** [comment]
Maybe we should add job to CI with next snapshot of Swift 3.1.

**Comment by norio-nomura** [comment]
Job added using 'swift-3.1-DEVELOPMENT-SNAPSHOT-2017-02-05-a` to Travis

**Comment by ikesyo** [comment]
Even if we conditionalize the unavailability only for Swift 3.1 on Linux, that is still API breaking (on the platform) and requires a major version bump (Result 4.x). So let's simply mark them unavailable for all platforms unconditionally and merge it into `master-next` branch, which is dedicated for Swift 3.1 changes. And leave the `master` branch as is (for Swift 3.0.x) for a while until we get Xcode 8.3 GM.

Does it make sense?

**Comment by norio-nomura** [comment]
I have removed `#if os(Linux)` from them.
I updated to use `@available(swift, deprecated: 3.0, obsoleted: 3.1, …` that would be intended to use on advance preparations of deprecation.
Same usage can be found in https://github.com/apple/swift/blob/swift-3.1-DEVELOPMENT-SNAPSHOT-2017-02-05-a/stdlib/public/SDK/CoreGraphics/CGFloat.swift.gyb#L339

**Comment by norio-nomura** [comment]
Event if we would use `master-next` for Result-4.x, I guess this PR could fit to that. 🙂

**Comment by norio-nomura** [comment]
I changed base branch to `master-next` and title.

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Pull request merged**
