### PR TITLE
#nodependencies

### LINKED ISSUE #28: Proposal: remove Either dependency
It's indisputable that `Result` is a kind of `Either`, but every added dependency is an additional burden for consumers, who I'm not convinced will use the `EitherType` functionality directly.

Furthermore, the Either [README](https://github.com/robrix/Either/blob/8d3f69d109436f74f68e4828a75be87eea12fa4b/README.md#use) even suggests that its functionality can be trivially added as an extension upon a pre-existing `Result` type. To me, this means that consumers should not be _required_ to build and link Either just to use a standardized `Result` type.

c.f. [the conversation from #reactivecocoa](https://reactivex.slack.com/archives/reactivecocoa/p1429157460000503)

/cc @nachosoto @saniul @tony

### PR DESCRIPTION
**Pull request by robrix**
Fixes #28.

### CODE REVIEW

**Comment by robrix** [comment]
Ready for review.

**Comment by rnapier** [comment]
:+1:

**Comment by robrix** [comment]
@jspahrsummers Any concerns with this approach?

**Comment by robrix** [comment]
It occurs to me we could make `Box` private:

- make a private `ResultState` `enum` with `analysis` and nothing else
- make `Result` a public `struct` with the real API

**Comment by jspahrsummers** [comment]
:100: All of the above sounds awesome. Thanks @robrix!

Hiding the `Result` cases might make pattern matching slightly more difficult, but `Box` kind of impaired that anyways (since you can't match through a box, IIRC). And maybe we could implement a custom `~=`? Not sure how that works.

**Comment by robrix** [comment]
Correct: you can’t match through anything but an `enum` or tuple. To the best of my knowledge, `~=` is limited to pass/fail, so that wouldn’t allow us to destructure, but we could maybe match against expected error/success values; and `analysis` recovers destructuring.

Gonna hide `Box` away now.

**Comment by robrix** [comment]
Alright, it’s done :mahjong:

**Comment by mdiep** [comment]
Can we get a release with this change? :grin:

**Comment by robrix** [comment]
@mdiep :+1:

**Comment by robrix** [comment]
@mdiep: https://github.com/antitypical/Result/releases/tag/0.3

**Comment by mdiep** [comment]
Thank you! :pray:

**Comment by robrix** [comment]
:bow: you’re welcome!

**Pull request merged**
