### PR TITLE
Update to swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a

### PR DESCRIPTION
**Pull request by norio-nomura**
Changes are affected by:
- [SE-0046 Establish consistent label behavior across all parameters including first labels](https://github.com/apple/swift-evolution/blob/master/proposals/0046-first-label.md)
- [SE-0055 Make unsafe pointer nullability explicit using Optional](https://github.com/apple/swift-evolution/blob/master/proposals/0055-optional-unsafe-pointers.md)

### CODE REVIEW

**Comment by norio-nomura** [comment]
Should we continue to support Swift 2.2 and 3 simultaneously?

**Comment by robrix** [comment]
> Should we continue to support Swift 2.2 and 3 simultaneously?

IMO yes, but I’m significantly less invested in this than I used to be so it’d be good to get others’ opinions. @antitypical/result: thoughts?

**Comment by rnapier** [comment]
@robrix do you mean less invested in Swift 2/3, less invested in Swift, or less invested in Result? I've found myself mostly drifting away from Result in my own work. I just found the impedance mismatch with the rest of Cocoa too high to be worth the trouble most of the time. I still throw together a custom Result when I need one for some particular problem, but I almost always just code up the couple of pieces I need rather than using a library. Curious about your experience.

**Comment by robrix** [comment]
I meant Swift; I don’t use it at all any more.

**Comment by mdiep** [comment]
> Should we continue to support Swift 2.2 and 3 simultaneously?

I think so, if possible.

**Comment by norio-nomura** [comment]
Thanks. I removed [WIP] tag.

**Comment by robrix** [comment]
@norio-nomura: Looks good to me :+1:

**Comment by mdiep** [comment]
Unfortunately, this needs a merge from master now.

**Comment by norio-nomura** [comment]
Updated.

**Comment by norio-nomura** [comment]
Thanks! :pray:

**Pull request merged**
