### PR TITLE
Re-added tvOS scheme

### PR DESCRIPTION
**Pull request by NachoSoto**
Now that `Xcode 7.1` is GM, this can be safely added back 😎

### CODE REVIEW

**Comment by NachoSoto** [comment]
Hmm I don't understand the build failure, the new scheme doesn't explain that error

**Comment by kylef** [comment]
Perhaps try switching to Xcode 7.1 in the travis config. The error message Xcode produces might be deceiving/wrong  ¯\_(ツ)_/¯.

Also, extra points for also testing tvOS in the travis config too.

**Comment by NachoSoto** [comment]
Ooooh of course. I'll try to that later, I hope they have an image already

**Comment by neilpa** [comment]
> I hope they have an image already

[They already do](https://github.com/travis-ci/travis-ci/issues/4799#issuecomment-150109763)

**Comment by NachoSoto** [comment]
Nice :)

**Comment by NachoSoto** [comment]
Tests passed! :tada:

**Comment by robrix** [comment]
@NachoSoto: I’ve invited you to the @antitypical/result team. Feel free to make a release at your leisure :+1:

**Comment by robrix** [comment]
(And thank you so much for the PR!)

**Comment by NachoSoto** [comment]
Thank you!

**Comment by NachoSoto** [comment]
Done: https://github.com/antitypical/Result/releases/tag/0.6.0-beta.5

**Comment by robrix** [comment]
:bow: thanks!

**Pull request merged**
