### PR TITLE
Fixed warnings for changes in Swift 3 syntax introduced in beta 3

### PR DESCRIPTION
**Pull request by NachoSoto**
Related: https://github.com/apple/swift-evolution/blob/master/proposals/0099-conditionclauses.md.

screen shot 2016-07-18 at 13 14 25

### CODE REVIEW

**Comment by NachoSoto** [comment]
Tests failing until Travis updates to beta 3.

**Comment by mdiep** [comment]
Since this is just a warning, I guess we'll wait until Travis updates to ß3.

**Comment by NachoSoto** [comment]
👍

**Comment by mdiep** [comment]
Superseded by #178.

**Pull request closed without merging**
