### PR TITLE
Re-enable `dematerialize` on Linux with 3.0-GM-CANDIDATE

### LINKED ISSUE #185: dematerialize() not working on linux
For the moment I try build our library Boilerplate for last swift 3 on linux but it depends on your Result library.
I run ```swift build``` and take such error:
> Compile Swift Module 'Boilerplate' (16 sources)
>/home/travis/build/crossroadlabs/Boilerplate/Sources/Boilerplate/Error.swift:151:16: error: value of >type 'Result<Value, Error>' has no member 'dematerialize'
>    return try result.dematerialize()
>               ^~~~~~ ~~~~~~~~~~~~~
>/home/travis/build/crossroadlabs/Boilerplate/Sources/Boilerplate/Container.swift:58:20: error: value >of type 'Result<Self.Value, Self.Error>' has no member 'dematerialize'
>        return try withdrawResult().dematerialize()
>                   ^~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~
><unknown>:0: error: build had 1 command failures
>error: exit(1): /home/travis/build/crossroadlabs/swift-3.0-PREVIEW-6-ubuntu14.04/usr/bin/swift->build-tool -f /home/travis/build/crossroadlabs/Boilerplate/.build/debug.yaml

What happens and when it can be fixed for linux?

### PR DESCRIPTION
**Pull request by ikesyo**
See #183, https://github.com/antitypical/Result/pull/182#discussion_r75149199 for the details. Closes #185.

### CODE REVIEW

**Comment by mdiep** [comment]
Should we be moving Result past the 3.0 builds for linux?

**Comment by ikesyo** [comment]
Looks like some updates to swiftenv are needed 😞

https://travis-ci.org/antitypical/Result/jobs/158895493

**Comment by kylef** [comment]
@ikesyo swiftenv has been updated, re triggered build here and it's now passing.

**Comment by mdiep** [comment]
@kylef Amazing! Thanks! 🎉

**Pull request merged**
