### PR TITLE
Update swift version to 4.2

### PR DESCRIPTION
**Pull request by aksswami**
Bump swift version to 4.2 and also increment pod version.

### CODE REVIEW

**Comment by ikesyo** [comment]
Thanks for the pr, but we would still like to keep Swift 4.1 compatiblity for a while. And also this is a source-breaking change so must be major version bump.

**Comment by aksswami** [comment]
I will update it for the major version bump. Can we have a swift-4.1 branch for swift 4.1 compatibility and master moved to latest swift version.

**Comment by norio-nomura** [comment]
Without any changes using the new features of Swift 4.2, what is the reason for updating to Swift 4.2?

**Comment by aksswami** [comment]
In my current project all pods are using Swift 4.2 except the Result and this gives me warning for upgrading the pods to Swift 4.2 . Yes, this is not an error/issue but still would like to clean things up.

**Comment by Jenus** [comment]
please merge this pull request

**Comment by Jenus** [comment]
please merge 2 commits into antitypical:master. Thanks

**Comment by aksswami** [comment]
I have changed the `SWIFT_VERSION` in Project Build settings to 4.2.

**Comment by larsschwegmann** [comment]
Any updates on this? These warnings are pretty annoying.

**Comment by norio-nomura** [comment]
Thanks!

**Pull request merged**
