### PR TITLE
Add mapError() & flatMapError()

### PR DESCRIPTION
**Pull request by inamiy**
Hi. I just wanted an Error type conversion, so I will send this pull request.

### CODE REVIEW

**Comment by robrix** [comment]
Thanks for the pull request!

I’m :+1: to the implementations, but I’m curious what others in @antitypical/result think about extending the API thus. Is this a common enough use case to be worth including in the framework itself?

**Comment by mdiep** [comment]
:+1:

**Comment by Thomvis** [comment]
I think it can definitely be useful e.g. when converting from NSError to your own error type or when using third party libraries that use Result in their API with their own error type. :+1: from me as well!

**Comment by robrix** [comment]
Works for me :+1:

**Comment by inamiy** [comment]
Thanks for merge :smiley:

**Pull request merged**
