### PR TITLE
Add conformance to LocalizedError for AnyError

### PR DESCRIPTION
**Pull request by ratkins**
Fixes https://github.com/antitypical/Result/issues/203

### CODE REVIEW

**Comment by ratkins** [comment]
Ok, that didn't go well. But I have no idea what the problem might be.

**Comment by ratkins** [comment]
Now I have some idea what the problem is: [a bug](https://bugs.swift.org/browse/SR-3565) in either the linux version of Foundation or SwiftGlibc.

Would you accept this PR with the implementation `#ifdef`'d out on Linux until the above is fixed?

**Comment by mdiep** [comment]
> Would you accept this PR with the implementation #ifdef'd out on Linux until the above is fixed?

I think that's acceptable. 👍 Definitely include a comment that links to the the bug.

**Comment by mdiep** [comment]
@ikesyo Would you mind giving this another look? I think you're probably better qualified to judge it.

**Pull request merged**
