### PR TITLE
3.0.0

### PR DESCRIPTION
**Pull request by mdiep**
I think we’re ready for a 3.0.0 release. Any objections? @antitypical/result

### CODE REVIEW

**Comment by norio-nomura** [comment]
Swift 3.0 GM Candidate has come.
https://swift.org/download/#previews
We should test on that for Linux.

**Comment by ikesyo** [comment]
@norio-nomura Thanks for the information. I updated #186 to use `3.0-GM-CANDIDATE`.

**Comment by mdiep** [comment]
Now that #186 has been merged, are we ready to ship 3.0.0?

**Comment by ikesyo** [comment]
Additionally, I'd like to get `CFBundleShortVersionString` of the `Info.plist`s updated too.

**Pull request merged**
