### PR TITLE
Add LocalizedError extenstion back to Linux as SR-3565 is fixed

### PR DESCRIPTION
**Pull request by ratkins**

### CODE REVIEW

**Comment by ratkins** [comment]
Hm. Bug [fixed on Feb 28th](https://bugs.swift.org/browse/SR-3565) and the snapshot Travis is running against is 3.1-March 1, so this should have worked? Don't have the resources to test this against a current 3.1 snapshot locally.

**Comment by ratkins** [comment]
Well this I don't understand. The PR supposedly fixing this was merged into Swift on March 2, Swift-3.1-RELEASE was cut on March 27 or thereabouts, Travis is testing against Swift-3.1-RELEASE and still failing 🤔 . Anyone have any ideas what might be going wrong?

**Comment by mdiep** [comment]
I have no idea. 😕

**Comment by ikesyo** [comment]
While https://github.com/apple/swift-corelibs-foundation/pull/861 was merged, `NSError` does not conform to `LocalizedError` protocol so `(nsError as Error).localizedDescription` does not return expected value unfortunately: https://github.com/apple/swift-corelibs-foundation/blob/swift-3.1-branch/Foundation/NSError.swift#L291-L314

**Comment by ikesyo** [comment]
> `NSError` does not conform to `LocalizedError` protocol so `(nsError as Error).localizedDescription` does not return expected value unfortunately

https://github.com/apple/swift-corelibs-foundation/pull/967 has been merged, so that should be fixed in Swift 4.0.

**Comment by ikesyo** [comment]
Closing this in favor of #227. Thanks for the pull request anyway!

**Pull request closed without merging**
