### PR TITLE
Enable CI

### LINKED ISSUE #6: CI

### PR DESCRIPTION
**Pull request by ishkawa**
Resolves #6.

- Run tests of Result-iOS and Result-Mac for each commits.
- Archive frameworks using `carthage archive` and upload artifacts for each git tags.

Some tasks are still not completed because I don't have admin rights.

- ~~Save developer identity at `script/certificates/development.p12`.~~
- ~~Save passphrase encrypted by `travis encrypt P12_PASSWORD=....` in .travis.yml.~~  
  ~~Ref: http://docs.travis-ci.com/user/encryption-keys/~~
- ~~Save GitHub API token encrypted by `travis setup releases`.~~  
  ~~Ref: http://docs.travis-ci.com/user/deployment/releases/~~
- [x] Enable CI on https://travis-ci.org.

I've tested automated release is working on [my own forked repository](https://github.com/ishkawa/Result/releases).

@robrix Could you complete remaining tasks?

**EDITED:** Removed tasks that requires signing items to make CI process simpler.

### CODE REVIEW

**Comment by NachoSoto** [comment]
> Archive frameworks using carthage archive and upload artifacts for each git tags.

Nice :+1:

**Comment by robrix** [comment]
I’ve enabled CI, but I’m not having a lot of success understanding the rest of the tasks. Additionally, I can’t seem to get the `travis` gem installed on 10.11. Does anyone know a workaround for that?

**Comment by ishkawa** [comment]
> Additionally, I can’t seem to get the travis gem installed on 10.11.

Oh, really? I also use 10.11 and can install `travis` by `[sudo] gem install travis`. If you still have trouble with installation, please email me following items:

- `.p12` of your developer identity.
  (ex. https://github.com/ishkawa/Result/tree/feature/travis-ci/script/certificates)

- Passphrase for the `.p12` file.
- GitHub API token of this repository.

I will setup `.travis.yml` using them! If you hesitate to send developer identity and its password, I can provide my own developer identity for this repository (if it's OK).

**Comment by kylef** [comment]
If you'd like to, it's also possible to automate pushing the podspec to CocoaPods trunk during the release process too.

See https://fuller.li/posts/automated-cocoapods-releases-with-ci/

**Comment by robrix** [comment]
@ishkawa: Curiously, I’m still having some trouble with the install.

I don’t really understand why we’d need a certificate for CI. IIRC setting up CI for `Set` didn’t require that, but perhaps things have changed since then?

I don’t mind you using your own certificate (I don’t actually have one at present), if you’re comfortable with that, but it sounds to me like that’s likely to get the certificate in question revoked since it’ll be public. (It’s _totally_ possible that I have just failed to understand this altogether.)

@kylef: That’s a splendid idea! I don’t know if @ishkawa will want to tackle that, but I’d be delighted to review a PR automating that.

**Comment by ishkawa** [comment]
> Curiously, I’m still having some trouble with the install.

:sob: 

> I don’t really understand why we’d need a certificate for CI. IIRC setting up CI for Set didn’t require that, but perhaps things have changed since then?

A certificate is required by `carthage build`. Running it without any certificates causes [this kind of error](https://travis-ci.org/ishkawa/Result/builds/83461112). If we remove auto-archiving and just run test tasks, we don't have to import a certificate. I think just testing is still valuable enough.

Now, we have to take a plan from following choices:

- Run testing only (No certificates are required).
- Run testing and archiving (Certificates and annual updates are required).

I'm not sure, but it might be better to start form the first choice.


@kylef Thank you for the cool guide. I'll consider whether to apply it after setup fundamental CI :smile:

**Comment by ishkawa** [comment]
To make CI tasks simpler, I've reverted some commits that requires signing items. I think automating release processes is still cool but releasing 1.0 is more important.

Now, CI is working and this PR is ready to merge!!

**Comment by robrix** [comment]
:heart: Thank you so much @ishkawa. I agree, it would be nice to automate releases, but having CI is a tremendous improvement! :bow:

**Pull request merged**
