### PR TITLE
Update version in podspec to 1.0.1

### PR DESCRIPTION
**Pull request by Thomvis**
We forgot to do this for the 1.0.1 release. The change is quite straight forward, but to make sure I'm not forgetting anything (like last time), I'd like a second pair of :eyes: to :+1:. Thanks!

### CODE REVIEW

**Comment by kylef** [comment]
Since there are new features, shouldn't it actually become 1.1.0 as per [semantic versioning](http://semver.org)?

> Given a version number MAJOR.MINOR.PATCH, increment the:

> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

**Comment by robrix** [comment]
Either way we should make sure the podspec & other notions of version (tags, etc) are in sync.

**Comment by gfontenot** [comment]
> shouldn't it actually become 1.1.0 as per semantic versioning?

It should have been 1.1.0, yeah. This is my fault. I suggested 1.0.1 because I didn't realize there were new features.

That being said, I agree that we should stay in sync with the tagged version. We'll try to do better with versioning moving forward.

**Comment by Thomvis** [comment]
So we should merge this in to make the 1.0.1 release complete, right?

**Comment by NachoSoto** [comment]
That's my bad, I should have realized when I made the release but I was on autopilot :/

**Comment by robrix** [comment]
:+1:, merging as-is.

**Comment by gfontenot** [comment]
Pushed to trunk

**Pull request merged**
