### PR TITLE
[travis] Test tvOS target and build watchOS target

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by mdiep** [comment]
Why isn't watchOS tested? :confused:

**Comment by ikesyo** [comment]
There is no `XCTest` in watchsimulator, so we can't run it.

**Comment by mdiep** [comment]
Wat.

**Comment by robrix** [comment]
> There is no `XCTest` in watchsimulator, so we can't run it nor build the test target.

Gary Oldman playing Jean-Baptiste Immanuel Zorg in The Fifth Element, laughing hysterically and then crying

**Pull request merged**
