### PR TITLE
Add an optional message parameter for NSLocalizedDescriptionKey to Result.static.error()

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by robrix** [comment]
My intention with the errors generated by this API was that they would be the underlying errors of higher-level errors generated by the consumer. That kind of obviates the need for a localized description in this API.

That said, wrapping errors isn’t super convenient.

@antitypical/result: Anybody else have any thoughts?

**Comment by jspahrsummers** [comment]
I'm hoping to avoid `NSError` as much as possible in Swift APIs, so anything that reduces the need to create them myself sounds good.

**Comment by robrix** [comment]
That’s good enough for me :+1:

**Comment by robrix** [comment]
Thanks for the PR, @ikesyo!

**Comment by ikesyo** [comment]
Thank you for merging! :metal:

**Pull request merged**
